;; キーバインド
(setq ns-command-modifier (quote meta))
(setq ns-alternate-modifier (quote super))
(keyboard-translate ?\C-h ?\C-?)
(global-set-key "\C-h" 'backward-delete-char)
(global-set-key "\C-cg" 'grep)
(global-set-key "\C-cc" 'compile)
(global-set-key "\M-g" 'goto-line)
(global-set-key "\C-xp" (lambda () (interactive) (other-window -1)))
(global-set-key "\M-N" 'next-error)
(global-set-key "\M-P" 'previous-error)
(global-set-key "\M-r" 'replace-string)
(global-set-key "\C-cso" 'occur-by-moccur)
(global-set-key "\C-z" nil) 

(when (fboundp 'electric-indent-mode) (electric-indent-mode -1))
